#' Compute average expression of gene sets across groups
#'
#' This function computes and visualizes the average expression of specified
#' gene sets (default: SE consensus markers) across specified groups.
#'
#' @param obj A Seurat object containing normalized gene expression data.
#'
#' @param group.by Character. Metadata column used to group cells for average expression
#' (default: "SE"). Each group will form one column in the output.
#'
#' @param genesets A named list of marker gene sets, where each element contains a vector of gene names.
#' If NULL (default), a predefined set of consensus SE marker genes will be used.
#' Marker genes not present in the dataset are automatically excluded. If no
#' markers from a given gene set are detected, NA values are returned for that set.
#'
#'
#' @return A list containing:
#' \describe{
#'   \item{AvgExp}{A scaled numeric matrix of average expression values,
#'   where rows correspond to marker gene sets and columns correspond to SEs.}
#'   \item{p}{A heatmap object generated by \code{HeatmapView} visualizing
#'   the average expression matrix.}
#' }
#'
#' @examples
#' \dontrun{
#' # Load Seurat object
#' obj <- readRDS("WU2161_seurat_obj.rds")
#'
#' # Normalize data
#' obj <- NormalizeData(obj)
#'
#' # Extract normalized expression matrix
#' normdata <- GetAssayData(obj, layer = "data")
#'
#' # Recover spatial ecotypes (SEs)
#' sepreds <- RecoverSE(normdata, celltypes = ctann)
#' obj <- AddMetaData(obj, sepreds)
#'
#' # Compute and visualize average expression of SE markers
#' res <- AverageMarkerExpression(obj, group.by = "SE")
#'
#' # Plot heatmap
#' draw(res$p)
#'
#' # Access averaged expression matrix
#' res$AvgExp
#' }
#' @export
#'
AverageMarkerExpression = function(obj, group.by = "SE", genesets = NULL){
  if(is.null(genesets)){
    genesets = readRDS(file.path(system.file("extdata", package = "SpatialEcoTyper"),
                                "SE_consensus_markers.rds"))
    row_title = "SE consensus markers"
  }else{
    row_title = "Custom gene sets"
  }
  pseudobulk = AverageExpression(obj, group.by = group.by, layer = "data")[[1]]
  pseudobulk = pseudobulk[rowSums(pseudobulk>0)>0, ]
  pseudobulk = log2(pseudobulk+1)
  pseudobulk = pseudobulk[, colnames(pseudobulk)!="NonSE"]
  avgexprs = lapply(genesets, function(x){
    x = intersect(x, rownames(pseudobulk))
    if (length(x) <= 0) {
      tmp_vec = rep(NA, ncol(pseudobulk))
      names(tmp_vec) = colnames(pseudobulk)
      return(tmp_vec)
    }
    colMeans(pseudobulk[rownames(pseudobulk)%in%x, , drop = FALSE])
  })
  avgexprs = do.call(rbind, avgexprs) ## row: genesets; column: SE recovery
  ses_not_na = rowSums(!is.na(avgexprs)) > 0
  avgexprs[ses_not_na, ] = ScaleData(avgexprs[ses_not_na, ], verbose = FALSE)

  p = HeatmapView(avgexprs, breaks = quantile(avgexprs, c(0.3, 0.5, 0.7, 0.85, 0.95)),
                  legend_height = 1, na_col = "#666666",
                  colors = pals::magma(7)[-c(4,6)],
                  column_title = "Spatial ecotypes", column_title_side = "bottom",
                  row_title = row_title,
                  show_row_names = TRUE, show_column_names = TRUE)
  return(list(AvgExp = avgexprs, p = p))
}
