#' Test Co-association Significance Between Cell States
#'
#' This function evaluates the statistical significance of co-association
#' of cell states within each SE. It computes within-SE average association scores
#' and compares them to a null distribution generated by permutation.
#' Diagonal values are ignored if they are all equal to 1 or NA.
#'
#' @param mat A numeric matrix of co-association or colocalization indices between states.
#' Row and column names should encode cell state labels (e.g. SE1_CD4T).
#' @param nperm Integer. Number of permutations used to estimate the null distribution.
#' Default is 1000.
#'
#' @return A named numeric vector of two-sided P-values for each SE,
#' representing the significance of within-SE co-association.
#'
#' @export
CoassociationTest = function(mat, nperm = 1000){
  if(all(diag(mat)==1) | all(is.na(diag(mat)))){
    diag(mat) = NA
  }
  avgIndices = function(x){
    ses1 = gsub("_.*", "", rownames(x))
    ses2 = gsub("_.*", "", colnames(x))
    avgs = unlist(lapply(unique(ses1), function(se){
      mean(x[ses1==se, ses2==se], na.rm = TRUE)
    }))
    names(avgs) = unique(ses1)
    avgs
  }
  Obs = avgIndices(mat)
  ses1 = gsub("_.*", "", rownames(mat))
  ses2 = gsub("_.*", "", colnames(mat))
  Perms = lapply(1:nperm, function(i){
    idx = sample(1:ncol(mat), ncol(mat))
    newmat = mat[, idx]
    colnames(newmat) = ses2
    avgIndices(newmat)
  })
  PermAvg = Reduce("+", Perms) / length(Perms)
  PermSD = apply(do.call(rbind, Perms), 2, sd, na.rm = TRUE)
  PermSD[PermSD==0] <- median(PermSD, na.rm = TRUE)
  Zscores = (Obs - PermAvg) / PermSD
  Zscores[is.na(Zscores)] = 0
  Pvals = pnorm(abs(Zscores), lower.tail = FALSE) * 2

  return(Pvals)
}
