#' Compute Cell State Colocalization Matrix
#'
#' This internal function computes a cell state–level colocalization matrix based on
#' spatial proximity of single cells. It first constructs a cell–cell neighborhood graph
#' using k-nearest neighbors within a specified radius, then aggregates neighbor
#' relationships to quantify interactions between cell states.
#'
#' @param scmeta A data.frame containing single-cell metadata. Each row represents
#' a cell. Row names should correspond to unique cell IDs.
#' @param coords Character vector specifying column names in \code{scmeta} for spatial
#' coordinates (e.g., \code{c("X", "Y")}).
#' @param CellState Character. Column name in \code{scmeta} specifying cell state
#' annotations (e.g., "SE1_CD4T").
#' @param radius Numeric. Maximum Euclidean distance threshold (in the same units
#' as \code{X} and \code{Y}) used to define neighboring cells. Default is 50.
#' @param k Integer. Number of nearest neighbors queried per cell before applying
#' the distance filter. Default is 200.
#' @param min.cell Integer. Minimum number of neighboring cells required for a
#' cell to be retained in the analysis. Cells with fewer neighbors are excluded
#' to reduce noise. Default is 10.
#'
#' @return A numeric matrix of size (number of cell states × number of cell states),
#' where each entry represents the normalized colocalization index between two
#' cell states.
#'
#' @details
#' The function performs the following steps:
#' \itemize{
#'   \item Identifies spatial neighbors using k-nearest neighbors within a specified radius
#'   \item Constructs a sparse binary cell–cell adjacency matrix
#'   \item Maps cells to their corresponding cell states
#'   \item Aggregates neighbor relationships to compute cell state–cell state interactions
#'   \item Normalizes interactions at both the cell and cell state levels
#' }
#'
#' Cells with fewer than \code{min.cell} neighbors are excluded to ensure
#' robustness of the colocalization estimates.
#'
#' @keywords internal
.colocalization <- function(scmeta, coords = c("X", "Y"),
                            CellState = "CellState",
                            radius = 50, k = 200,
                            min.cell = 10){

  coords <- as.matrix(scmeta[, coords])
  knn <- RANN::nn2(data = coords, query = coords, k = k)
  knn$nn.idx[knn$nn.dists > radius] <- NA

  # ---- Cell-cell adjacency ----
  idx.array <- rep(seq_len(nrow(knn$nn.idx)), rowSums(!is.na(knn$nn.idx[, -1])))
  idx.array <- cbind(idx.array, na.omit(as.vector(t(knn$nn.idx[, -1]))))

  cellneighbors <- Matrix::Matrix(0, nrow = nrow(scmeta), ncol = nrow(scmeta), sparse = TRUE)
  rownames(cellneighbors) <- rownames(scmeta)
  colnames(cellneighbors) <- rownames(scmeta)
  cellneighbors[idx.array] <- 1

  # ---- Cell-state mapping ----
  states <- unique(scmeta[[CellState]])
  cell2state <- Matrix::Matrix(0, nrow = nrow(scmeta), ncol = length(states), sparse = TRUE)
  rownames(cell2state) <- rownames(scmeta)
  colnames(cell2state) <- states

  idx <- cbind(seq_len(nrow(scmeta)), match(scmeta[[CellState]], states))
  cell2state[idx] <- 1

  # ---- Aggregate neighbors ----
  cellstateneighbors <- cellneighbors %*% cell2state
  keep <- rowSums(cellstateneighbors) >= min.cell
  cellstateneighbors <- cellstateneighbors[keep, , drop = FALSE]

  cellstateneighbors <- cellstateneighbors / rowSums(cellstateneighbors)

  W <- t(cell2state[rownames(cellstateneighbors), , drop = FALSE])
  W <- W / rowSums(W)

  stateneighbors <- W %*% cellstateneighbors
  stateneighbors <- stateneighbors[sort(rownames(stateneighbors)),
                                   sort(colnames(stateneighbors))]
  return(as.matrix(stateneighbors))
}

#' Evaluate Cell State Colocalization
#'
#' This function computes cell state colocalization indices and assesses their
#' statistical significance using permutation testing. Observed colocalization
#' is compared against a null distribution generated by shuffling cell state
#' labels within each cell type.
#'
#' @param scmeta A data.frame containing single-cell metadata, where each row
#' represents a cell. Row names should correspond to unique cell IDs.
#' @param coords Character vector specifying column names in \code{scmeta} for spatial
#' coordinates (e.g., \code{c("X", "Y")}).
#' @param SE Character. Column name in \code{scmeta} specifying spatial ecotype labels.
#' @param CellType Character. Column name in \code{scmeta} specifying cell type annotations.
#' Permutations are performed within each cell type to preserve cell-type composition.
#' @param radius Numeric. Maximum Euclidean distance threshold (in the same units
#' as \code{X} and \code{Y}) for defining neighboring cells. Default is 50.
#'
#' @param k Integer. Number of nearest neighbors queried per cell before applying
#' the distance filter. Default is 200.
#' @param min.cell Integer. Minimum number of neighboring cells required for a
#' cell to be included in the analysis. Cells with fewer neighbors are excluded.
#' Default is 10.
#' @param nperm Integer. Number of permutations used to generate the null distribution.
#' Default is 1000.
#' @param test Logical. Whether to compute statistical significance (P-values).
#' If TRUE, both Z-scores and P-values are returned; otherwise only Z-scores are returned.
#' Default is TRUE.
#' @param ncores Integer. Number of cores to use for parallel computation of permutations.
#' Default is 16.
#'
#' @return
#' If \code{test = TRUE}, a list containing:
#' \describe{
#'   \item{ColocIndex}{A matrix of Z-scored colocalization indices between all cell states}
#'   \item{Pval}{A vector of P-values assessing co-association significance.}
#' }
#'
#' If \code{test = FALSE}, returns only the Z-score matrix of colocalization indices.
#'
#' @details
#' The function performs the following steps:
#' \itemize{
#'   \item Computes observed cell state colocalization using spatial neighbor relationships
#'   \item Generates a null distribution by permuting cell state labels within each cell type
#'   \item Computes mean and standard deviation of permuted colocalization matrices
#'   \item Standardizes observed values into Z-scores
#'   \item Optionally computes statistical significance using \code{CoassociationTest}
#' }
#'
#' This approach preserves cell-type composition while testing whether spatial
#' organization of cell states deviates from random expectation.
#'
#' @importFrom parallel mclapply
#' @importFrom dplyr group_by mutate
#' @importFrom rlang .data
#' @export

Colocalization <- function(scmeta, coords = c("X", "Y"),
                           SE = "SE", CellType = "CellType",
                           radius = 50, k = 200, min.cell = 10,
                           nperm = 1000, test = TRUE, ncores = 16){

  required <- c(coords, SE, CellType)
  if(!all(required %in% colnames(scmeta))){
    missing_cols <- setdiff(required, colnames(scmeta))
    stop("Missing required columns in scmeta: ", paste(missing_cols, collapse = ", "), ".")
  }
  scmeta$CellState = paste0(scmeta[[SE]], "_", scmeta[[CellType]])

  if (is.null(rownames(scmeta))) {
    rownames(scmeta) <- paste0("Cell", seq_len(nrow(scmeta)))
  }
  scmeta$CID <- rownames(scmeta)

  # ---- Observed ----
  Obs <- .colocalization(scmeta, coords = coords, CellState = "CellState",
                         radius = radius, k = k, min.cell = min.cell)

  # ---- Permutations ----
  Permutes <- parallel::mclapply(seq_len(nperm), function(i){
    tmpmeta <- scmeta %>% dplyr::group_by(.data[[CellType]]) %>%
      dplyr::mutate(CellState = sample(CellState)) %>%
      as.data.frame()
    rownames(tmpmeta) <- tmpmeta$CID
    .colocalization(tmpmeta, coords = coords, CellState = "CellState",
                    radius = radius, k = k, min.cell = min.cell)
  }, mc.cores = ncores)

  # ---- Mean / SD ----
  PermuteAvg <- Reduce("+", Permutes) / length(Permutes)
  PermuteSD <- aggregate(do.call(rbind, Permutes),
                         by = list(State = unlist(lapply(Permutes, rownames))), sd)
  rownames(PermuteSD) <- PermuteSD$State
  PermuteSD <- as.matrix(PermuteSD[, -1])
  PermuteSD[PermuteSD == 0] <- 1

  # ---- Z-score ----
  Zscores <- (Obs - PermuteAvg) / PermuteSD
  Zscores[is.na(Zscores)] = 0

  if (test) {
    Pval <- CoassociationTest(Zscores, nperm = nperm)
    return(list(ColocIndex = Zscores, Pval = Pval))
  } else {
    return(Zscores)
  }
}


#' Colocalization Heatmap Visualization
#'
#' Generates a heatmap to visualize the colocalization indices between SE cell states,
#' optionally annotating significance levels based on p-values. The heatmap includes customizable row and
#' column annotations, color scales, clustering, and significance indicators.
#'
#' @param ColocIndex A numeric matrix of colocalization indices. Row names should be formatted as "SE_CellType".
#' @param Pval Optional named numeric vector of p-values for each SE. Names should match SE identifiers.
#' @param breaks Numeric vector specifying break points for the heatmap color scale. Default is the 55th, 75th, and 90th quantiles of \code{ColocIndex}.
#' @param colors Character vector of colors for the heatmap. Default is \code{c("#f2f0f7", "#cbc9e2", "#54278f")}.
#' @param legend_height Numeric, height of the legend. Default is 1.
#' @param cluster_rows Logical, whether to cluster rows. Default is FALSE.
#' @param cluster_cols Logical, whether to cluster columns. Default is FALSE.
#' @param show_left_legend Logical, whether to show the left-side legend. Default is FALSE.
#' @param show_column_names Logical, whether to show column names. Default is FALSE.
#' @param show_row_names Logical, whether to show row names. Default is FALSE.
#' @param ... Additional arguments passed to \code{HeatmapView}.
#'
#' @return A ComplexHeatmap object visualizing colocalization between cell states.
#'
#' @details
#' This function splits the row names into two parts: SE (spatial ecosystem) and CellType,
#' and assigns colors to both categories. If \code{Pval} is provided, significance levels are
#' annotated using "*", "**", "***", or "****" for p-values <0.05, <0.01, <0.001, and <0.0001, respectively.
#' The heatmap can be customized with clustering, annotations, and color scales.
#'
#' @examples
#' # Example usage
#' col_matrix <- matrix(runif(25), nrow = 5)
#' rownames(col_matrix) <- c("SE1_CD4T", "SE1_CD8T", "SE2_CD4T", "SE2_CD8T", "SE3_CD4T")
#' colnames(col_matrix) <- c("SE1_CD4T", "SE1_CD8T", "SE2_CD4T", "SE2_CD8T", "SE3_CD4T")
#' pvals <- c(SE1 = 0.01, SE2 = 0.2, SE3 = 0.0005)
#' CooccurrenceHeatmapView(col_matrix, Pval = pvals)
#'
#' @import ComplexHeatmap
#' @importFrom grid grid.text
#' @export
CooccurrenceHeatmapView <- function(ColocIndex, Pval = NULL,
                                      breaks = quantile(ColocIndex, c(0.55, 0.75, 0.9)),
                                      colors = c("#f2f0f7", "#cbc9e2", "#54278f"),
                                      legend_height = 1,
                                      cluster_rows = FALSE, cluster_cols = FALSE,
                                      show_left_legend = FALSE, show_column_names = FALSE,
                                      show_row_names = FALSE, ...){
  requireNamespace("ComplexHeatmap")
  gg = ColocIndex
  rowann = data.frame(SE = gsub("_.*", "", rownames(gg)),
                      CellType = gsub(".*_", "", rownames(gg)),
                      row.names = rownames(gg))
  se_colors = getColors(n = length(unique(rowann$SE)), palette = 1)
  names(se_colors) = unique(rowann$SE)
  celltype_cols = getColors(n = length(unique(rowann$CellType)), palette = 2)
  names(celltype_cols) = unique(rowann$CellType)

  if(!is.null(Pval)){
    rowann$Pval = Pval[rowann$SE]
    rowann$Signif = "ns"
    rowann$Signif[rowann$Pval<0.05] = "*"
    rowann$Signif[rowann$Pval<0.01] = "**"
    rowann$Signif[rowann$Pval<0.001] = "***"
    rowann$Signif[rowann$Pval<0.0001] = "****"
    Signif = rowann[!duplicated(rowann$SE), "Signif"]
    align_to = lapply(unique(rowann$SE), function(se){ which(rowann$SE==se) })
    names(align_to) = unique(rowann$SE)

    p = HeatmapView(gg, breaks = breaks, colors = colors,
                    legend_height = legend_height,
                     cluster_rows = cluster_rows,
                     cluster_cols = cluster_cols,
                     show_left_legend = show_left_legend,
                     show_column_names = show_column_names,
                     show_row_names = show_row_names,
                     top_ann = rowann[, -c(3,4)],
                     left_ann = rowann[, -c(3,4)],
                     top_ann_col = list(SE = se_colors, CellType = celltype_cols),
                     left_ann_col = list(SE = se_colors, CellType = celltype_cols),
                     right_ann = rowAnnotation(SE = anno_block(align_to = align_to,
                                                               labels = Signif,
                                                               panel_fun = function(index, nm) {
                                                                 grid.text(rowann$Signif[index[1]], 0.5, 0.5)
                                                               })),
                     ...)
  }else{
    p = HeatmapView(gg, breaks = breaks, colors = colors,
                   legend_height = legend_height,
                   cluster_rows = cluster_rows,
                   cluster_cols = cluster_cols,
                   show_left_legend = show_left_legend,
                   show_column_names = show_column_names,
                   show_row_names = show_row_names,
                   top_ann = rowann[, -c(3,4)],
                   left_ann = rowann[, -c(3,4)],
                   top_ann_col = list(SE = se_colors, CellType = celltype_cols),
                   left_ann_col = list(SE = se_colors, CellType = celltype_cols),
                   ...)
  }
  return(p)
}


