#' Internal function for computing Moran's I
#'
#' Internal helper function to compute Moran's I statistic for each spatial ecotype (SE)
#' given a spatial weights matrix. For each unique SE label, a binary vector is constructed
#' (1 = cells belonging to the SE, 0 = others), and Moran's I is calculated to quantify
#' spatial autocorrelation.
#'
#' @param ses A vector of spatial ecotype (SE) labels for each cell.
#' @param listw A spatial weights object of class \code{listw}, typically generated
#'   using k-nearest neighbors.
#' @param ncores Integer specifying the number of cores for parallel computation.
#'
#' @return A named numeric vector of Moran's I values for each SE.
#'   Names correspond to unique SE labels.
#'
#' @details
#' This function binarizes each SE and computes Moran's I independently.
#' @importFrom spdep Szero
#'
#' @keywords internal
.moran = function(ses, listw, ncores = 1){
  moran_results = mclapply(sort(unique(ses)), function(se){
    clusters = rep(0, length(ses))
    clusters[ses==se] = 1
    moran_result = spdep::moran(clusters, listw = listw,
                         n = length(clusters),
                         S0 = spdep::Szero(listw))
    moran_result$I
  }, mc.cores = ncores)
  moran_results = unlist(moran_results)
  names(moran_results) = sort(unique(ses))
  moran_results
}

#' Compute Normalized Moran's I for Spatial Ecotypes
#'
#' Computes a normalized Moran's I statistic to quantify spatial autocorrelation
#' of cell states (e.g., spatial ecotypes) while accounting for cell-type structure.
#' The observed Moran's I is compared against a null distribution generated by
#' permuting cell state labels within each cell type.
#'
#' @param scmeta A data.frame containing single-cell metadata. Each row represents a cell.
#' @param coords Character vector specifying column names for spatial
#' coordinates (e.g., \code{c("X", "Y")}).
#' @param SE Character. Column name specifying spatial ecotype (or cell state) labels.
#' @param CellType Character. Column name specifying cell type annotations.
#' @param nperm Integer. Number of permutations used to estimate the null distribution.
#' Default is 1000.
#' @param k Integer. Number of nearest neighbors used to construct the spatial graph.
#' Default is 3.
#' @param ncores Integer. Number of cores used in Moran’s I computation (if parallelized).
#' Default is 1.
#' @return A numeric vector of Z-scores representing normalized Moran's I values
#' for each cell state.
#'
#' @details
#' The function performs the following steps:
#' \itemize{
#'   \item Constructs a k-nearest neighbor graph based on spatial coordinates
#'   \item Computes observed Moran’s I for cell state labels
#'   \item Generates a null distribution by permuting cell state labels within each cell type
#'   \item Normalizes observed Moran’s I into Z-scores using the permutation mean and standard deviation
#' }
#'
#' This approach preserves cell-type composition while testing whether spatial
#' organization of cell states deviates from random expectation.
#'
#' @importFrom spdep knearneigh knn2nb nb2listw
#' @importFrom dplyr group_by mutate ungroup pull
#' @importFrom rlang .data
#' @export
#'
ComputeNormalizedMoranI <- function(scmeta, coords = c("X", "Y"),
                                    SE = "SE", CellType = "CellType",
                                    nperm = 1000, k = 3, ncores = 1){

  # ---- Input validation ----
  required <- c(coords, SE, CellType)
  if(!all(required %in% colnames(scmeta))){
    missing_cols <- setdiff(required, colnames(scmeta))
    stop("Missing required columns in scmeta: ", paste(missing_cols, collapse = ", "), ".")
  }
  if(is.null(rownames(scmeta))){
    rownames(scmeta) <- paste0("Cell", seq_len(nrow(scmeta)))
  }
  coords_df <- as.data.frame(scmeta[, coords, drop = FALSE])

  # ---- KNN graph ----
  knn <- spdep::knearneigh(as.matrix(coords_df), k = k)
  nb <- spdep::knn2nb(knn, row.names = rownames(coords_df))
  listw <- spdep::nb2listw(nb, style = "W", zero.policy = TRUE)

  # ---- Observed Moran's I ----
  Obs <- .moran(scmeta[[SE]], listw, ncores = ncores)

  # ---- Permutations ----
  Bgs <- lapply(seq_len(nperm), function(ii){
    perm_se <- scmeta %>%
      dplyr::group_by(.data[[CellType]]) %>%
      dplyr::mutate(tmp = sample(.data[[SE]])) %>%
      dplyr::ungroup() %>% dplyr::pull(tmp)

    .moran(perm_se, listw, ncores = ncores)
  })
  Bgs <- do.call(rbind, Bgs)

  # ---- Z-score normalization ----
  mu <- colMeans(Bgs)
  sigma <- apply(Bgs, 2, sd)
  sigma[sigma == 0] <- 1

  zscore <- (Obs - mu) / sigma

  return(zscore)
}

